version: "3.9"
services:
  splitter:
    build: ./2_splitter
    depends_on:
      alerts-queue-1:
        condition: service_healthy
      data-queue-1:
        condition: service_healthy
    ports:
      - "8080:80"

  producer-alerts:
    build: ./3_sharding
    environment:
      - ALERTS_QUEUE_PRIMARY=alerts-queue-1
      - ALERTS_QUEUE_SECONDARY=alerts-queue-2
      - QUEUE_ALERT=alert_queue
    depends_on:
      alerts-queue-1:
        condition: service_healthy
    ports:
      - "9090:80"
  
  producer-data:
    build: ./4_sharding
    environment:
      - DATA_QUEUE_PRIMARY=data-queue-1
      - DATA_QUEUE_SECONDARY=data-queue-2
      - QUEUE_NAME=data_queue
    depends_on:
      data-queue-1:
        condition: service_healthy
    ports:
      - "8082:80"

  alerts-queue-1:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "5672:5672"
    expose:
      - "5672"

  alerts-queue-2:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "5673:5672"
    expose:
      - "5673"

  data-queue-1:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "5674:5672"
    expose:
      - "5674"

  data-queue-2:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "5675:5672"
    expose:
      - "5675"

  11_servidor_ose_1:
    build: ./11_servidor_ose_1
    ports:
      - "8000:8000"
    environment:
      - ALERTS_QUEUE_PRIMARY=alerts-queue-1
      - ALERTS_QUEUE_SECONDARY=alerts-queue-2
      - QUEUE_ALERT=alert_queue
      - DATA_QUEUE_PRIMARY=data-queue-1
      - DATA_QUEUE_SECONDARY=data-queue-2
      - DJANGO_SETTINGS_MODULE=ose_core.settings
      - QUEUE_DATA=data_queue
      - PYTHONUNBUFFERED=1
    depends_on:
    - alerts-queue-1
    - alerts-queue-2
    - data-queue-1
    - data-queue-2
    - ose_db

  12_servidor_ose_2:
    build: ./12_servidor_ose_2
    ports:
      - "8081:8000"
    environment:
      - ALERTS_QUEUE_PRIMARY=alerts-queue-1
      - ALERTS_QUEUE_SECONDARY=alerts-queue-2
      - QUEUE_ALERT=alert_queue
      - DATA_QUEUE_PRIMARY=data-queue-1
      - DATA_QUEUE_SECONDARY=data-queue-2
      - QUEUE_DATA=data_queue
      - PYTHONUNBUFFERED=1
    depends_on:
    - alerts-queue-1
    - alerts-queue-2
    - data-queue-1
    - data-queue-2
    - ose_db
  
  ose_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ose_db
    volumes:
      - postgres_data_ose:/var/lib/postgresql/data
    command: postgres -c 'shared_preload_libraries=pg_stat_statements' -c 'log_statement=all'
  
  nginx_ose:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx_ose.conf:/etc/nginx/nginx.conf
    depends_on:
      - 11_servidor_ose_1
      - 12_servidor_ose_2

  14_servidor_ine_1:
    build: ./14_servidor_ine_1
    ports:
      - "8008:8000"
    environment:
      - DATA_QUEUE_PRIMARY=data-queue-1
      - DATA_QUEUE_SECONDARY=data-queue-2
      - QUEUE_NAME=data_queue
      - PYTHONUNBUFFERED=1
    depends_on:
    - data-queue-1
    - data-queue-2

volumes:
  postgres_data_ose:

  