version: "3.9"
services:
  splitter:
    build: ./2_splitter
    depends_on:
      alerts-queue-1:
        condition: service_healthy
    ports:
      - "8080:80"

  producer-alerts:
    build: ./3_sharding
    environment:
      - ALERTS_QUEUE_PRIMARY=alerts-queue-1
      - ALERTS_QUEUE_SECONDARY=alerts-queue-2
      - QUEUE_NAME=test_queue
    depends_on:
      alerts-queue-1:
        condition: service_healthy
    ports:
      - "8081:80"

  alerts-queue-1:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5672:5672"
    expose:
      - "5672"

  alerts-queue-2:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "5673:5672"
    expose:
      - "5672"

  11_servidor_ose_1:
    build: ./11_servidor_ose_1
    ports:
      - "8000:8000"
    environment:
      - ALERTS_QUEUE_PRIMARY=alerts-queue-1
      - ALERTS_QUEUE_SECONDARY=alerts-queue-2
      - QUEUE_NAME=test_queue
      - PYTHONUNBUFFERED=1
    depends_on:
    - alerts-queue-1
    - alerts-queue-2


