# Generated by Django 4.2.1 on 2023-06-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ose_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flow', models.FloatField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Alert',
            new_name='Alerts',
        ),
    ]
