# Use an official Python runtime as the base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app/ose_core/

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r ../requirements.txt

# Install Gunicorn
RUN pip install gunicorn

# Copy the Django project code to the container
COPY . /app/

# Expose the port that Django runs on (default: 8000)
EXPOSE 8000

# Run the Celery worker and the Django application using Gunicorn
CMD celery -A ose_core worker --loglevel=info & gunicorn ose_core.wsgi:application --bind 0.0.0.0:8000 --capture-output --log-level debug